project: 
  type: website
  
params:
  assign_points: 35  # Points to be consistent across all assignments

website: 
  page-navigation: true
  title: "PSYC 641 - Graduate Methods" 
  site-url: "https://dharaden.github.io/psyc641-s26"
  
  repo-url: https://github.com/dharaden/psyc641-s26 
  repo-actions: [edit, issue]
  
  open-graph: true

  page-footer:
    right: "This page is built with â˜• and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Dustin Haraden, 2026"
    
  sidebar:
    logo: "images/641_hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/dharaden/psyc641-s26
        text: "GitHub"
      - icon: chalkboard
        href: https://mycourses.rit.edu/d2l/login
        text: "myCourses"
        

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "Course Overview"
      - href: course-syllabus.qmd
        text: "Schedule"
      - href: previous-years.qmd
        text: "Previous Years"

format:
  html:
    theme: theme.scss
    mainfont: Nunito
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual


filters:
  - include-files.lua
  - quarto
